# This GitHub Actions workflow is triggered when a new release is created.
# It builds the package on an Ubuntu environment,
# installs the required dependencies, and publishes the package to the npm registry.
# The workflow requires a secret named NPM_TOKEN to be set up in the repository's secrets,
# which is used as the authentication token for npm publish command. 

name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}